In [1]:
import numpy as np
print("\nMatrix1 details:")
R1 = int(input("Enter the no of rows:"))
C1 = int(input("Enter the no of coloumn:"))
print("Enter the entries in a single line: ")
entries = list(map(int, input().split()))
m1 = np.array(entries).reshape(R1,C1)
print("\nMatrix_1: \n",m1)

print("\nMatrix2 details:")
R2 = int(input("Enter the no of rows:"))
C2= int(input("Enter the no of coloumn:"))
print("Enter the entries in a single line: ")
entries = list(map(int, input().split()))
m2 = np.array(entries).reshape(R2,C2)
print("\nMatrix_2: \n",m2)


Matrix1 details:


Enter the no of rows: 2
Enter the no of coloumn: 2


Enter the entries in a single line: 


 1 2 3 4



Matrix_1: 
 [[1 2]
 [3 4]]

Matrix2 details:


Enter the no of rows: 2
Enter the no of coloumn: 2


Enter the entries in a single line: 


 2 3 4 5



Matrix_2: 
 [[2 3]
 [4 5]]


In [2]:
#1
print("1.Dot product")
print(np.dot(m1,m2))

1.Dot product
[[10 13]
 [22 29]]


In [10]:
#2
print("2.Transpose")
print("\nTranspose of matrix1")
print(np.transpose(m1))
print("Transpose of matrix2")
print(np.transpose(m2))

2.Transpose

Transpose of matrix1
[[1 3]
 [2 4]]
Transpose of matrix2
[[2 4]
 [3 5]]


In [11]:
#3
print("3.Trace")
print("\nTrace of matrix1")
print(np.trace(m1))
print("Trace of matrix2")
print(np.trace(m2))

3.Trace

Trace of matrix1
5
Trace of matrix2
7


In [12]:
#4
print("4.Rank")
print("\nThe rank of matrix_1 :",np.linalg.matrix_rank(m1),"\nThe rank of matrix_2 :",np.linalg.matrix_rank(m2))

4.Rank

The rank of matrix_1 : 2 
The rank of matrix_2 : 2


In [13]:
#5
print("5.determinent")
print("\nThe determinent of matrix_1 :",int(np.linalg.det(m1)),"\nThe determinent of matrix_2 :",int(np.linalg.det(m2)))

5.determinent

The determinent of matrix_1 : -2 
The determinent of matrix_2 : -2


In [15]:
print("6.Inverse")
print("\nThe inverse of matrix_1 : \n",np.linalg.inv(m1),"\n The inverse of matrix_2 : \n",np.linalg.inv(m2))


6.Inverse

The inverse of matrix_1 : 
 [[-2.   1. ]
 [ 1.5 -0.5]] 
 The inverse of matrix_2 : 
 [[-2.5  1.5]
 [ 2.  -1. ]]


In [18]:
#Eigenvalues and eigenvectors

import numpy as np
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("a = ")
print(a)
w, v = np.linalg.eig(a)
print("\nEigenvalues:")
print(w)
print("\nEigenvectors:")
print(v)


a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Eigenvalues:
[5. 1. 1.]

Eigenvectors:
[[-0.57735027 -0.90453403  0.82529864]
 [-0.57735027  0.30151134 -0.52125218]
 [-0.57735027  0.30151134  0.21720572]]
