In [14]:
#1:Numpy program to create an element wise comparison of tw given arrays.
import numpy as np
arr1 = np.array([3, 2, 3])
arr2 = np.array([1, 6, 3])
print("Array1:",arr1)
print("Array2:",arr2)

print("\nElement wise comparison:")
print("\ngreater")
print("--------------")
print(np.greater(arr1,arr2))
print("\ngreater_equal")
print("--------------")
print(np.greater_equal(arr1,arr2))
print("\nless")
print("--------------")
print(np.less(arr1,arr2))
print("\nless_equal")
print("--------------")
print(np.less_equal(arr1,arr2))



Array1: [3 2 3]
Array2: [1 6 3]

Element wise comparison:

greater
--------------
[ True False False]

greater_equal
--------------
[ True False  True]

less
--------------
[False  True False]

less_equal
--------------
[False  True  True]


In [15]:
#2:Numpy program to create an element wise comparison of tw given arrays.
import numpy as np
x=np.arange(30,71,2)
print("Even integers from 30 to 70:")
print(x) 

Even integers from 30 to 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [16]:
#3:Numpy program to create 3*3 identity matrix
import numpy as np
Imatrix=np.identity(3)
print('Identity matrix:')
print(Imatrix)

Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
#4:Numpy program to create a vector  with values from 0 to 20 and change th sign of the numbers in the range from 9 to 15.
import numpy as np
x = np.arange(21)
print("Original vector:")
print(x)
print("Modified vector:")
x[(x >= 9) & (x <= 15)] *= -1
print(x)

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Modified vector:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [17]:
#5:Numpy program to create a 5*5 zero matrix with elements on the main diagonal equal to 1,2,3,4,5.
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [20]:
#6:Numpy program to compute sum of all elements,sum of each column and sum of each row of a given array.
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print("Initial array :")
print(x)
print("Sum of all elements of array:")
print(np.sum(x))
print("Sum of each column of array:")
print(np.sum(x, axis=0))
print("Sum of each row of array:")
print(np.sum(x, axis=1))

Initial array :
[[1 2 3]
 [4 5 6]]
Sum of all elements of array:
21
Sum of each column of array:
[5 7 9]
Sum of each row of array:
[ 6 15]
