In [12]:
#Dot product

import numpy as np

# Matrices as ndarray objects
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7], [8, 9, 10]])
print("a", type(a))
print(a)
print("\nb", type(b))
print(b)

# Matrices as matrix objects
c = np.matrix([[1, 2], [3, 4]])
d = np.matrix([[5, 6, 7], [8, 9, 10]])
print("\nc", type(c))
print(c)
print("\nd", type(d))
print(d)
print("\ndot product of two ndarray objects")
print(np.dot(a, b))
print("\ndot product of two matrix objects")
print(np.dot(c, d))

a <class 'numpy.ndarray'>
[[1 2]
 [3 4]]

b <class 'numpy.ndarray'>
[[ 5  6  7]
 [ 8  9 10]]

c <class 'numpy.matrix'>
[[1 2]
 [3 4]]

d <class 'numpy.matrix'>
[[ 5  6  7]
 [ 8  9 10]]

dot product of two ndarray objects
[[21 24 27]
 [47 54 61]]

dot product of two matrix objects
[[21 24 27]
 [47 54 61]]


In [14]:
#Transpose

import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
print("a = ")
print(a)

print("\nWith np.transpose(a) function")
print(np.transpose(a))

print("\nWith ndarray.transpose() method")
print(a.transpose())

print("\nWith ndarray.T short form")
print(a.T)

a = 
[[1 2]
 [3 4]
 [5 6]]

With np.transpose(a) function
[[1 3 5]
 [2 4 6]]

With ndarray.transpose() method
[[1 3 5]
 [2 4 6]]

With ndarray.T short form
[[1 3 5]
 [2 4 6]]


In [13]:
#Trace

import numpy as np
a = np.array([[2, 2, 1],[1, 3, 1],[1, 2, 2]])
print("a = ")
print(a)
print("\nTrace:", a.trace())
print("Trace:", sum(a.diagonal()))

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Trace: 7
Trace: 7


In [16]:
#Rank

import numpy as np
a = np.arange(1, 10)
a.shape = (3, 3)
print("a = ")
print(a)
rank = np.linalg.matrix_rank(a)
print("\nRank:", rank)

a = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank: 2


In [15]:
#Determinant

import numpy as np
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("a = ")
print(a)
det = np.linalg.det(a)
print("\nDeterminant:", np.round(det))

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Determinant: 5.0


In [17]:
#Inverse

import numpy as np
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("a = ")
print(a)
det = np.linalg.det(a)
print("\nDeterminant:", np.round(det))
inv = np.linalg.inv(a)
print("\nInverse of a = ")
print(inv)

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Determinant: 5.0

Inverse of a = 
[[ 0.8 -0.4 -0.2]
 [-0.2  0.6 -0.2]
 [-0.2 -0.4  0.8]]


In [11]:
#Eigenvalues and eigenvectors

import numpy as np
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("a = ")
print(a)
w, v = np.linalg.eig(a)
print("\nEigenvalues:")
print(w)
print("\nEigenvectors:")
print(v)

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Eigenvalues:
[5. 1. 1.]

Eigenvectors:
[[-0.57735027 -0.90453403  0.82529864]
 [-0.57735027  0.30151134 -0.52125218]
 [-0.57735027  0.30151134  0.21720572]]
