In [10]:
#7:numpy program to save a given array to a text file and load it.
import numpy as np
import os
x = np.arange(6).reshape(3, 2)
print("Initial array:")
print(x)
header = 'col1 col2 col3'
np.savetxt('t.txt', x, fmt="%d", header=header) 
print("Final array:")
result = np.loadtxt('t.txt')
print(result)

Initial array:
[[0 1]
 [2 3]
 [4 5]]
Final array:
[[0. 1.]
 [2. 3.]
 [4. 5.]]


In [12]:
#8:numpy program to check whether two arrays are equal(element wise) or not

import numpy as np
x = np.array([1,7,8])
print("1st array:")
print(x)
y = np.array([1,7,8]) #false if y=np.array([3,4,8])
print("2nd array:")
print(y)
print("after testing")
array_equal = np.allclose(x, y)
print(array_equal)

1st array:
[1 7 8]
2nd array:
[1 7 8]
after testing
True


In [14]:
#9:numpy program to create 4*4 array with random values,now create a new array from the said array swapping first and last rows

import numpy as np
n = np.arange(16).reshape(-1, 4)
print("Initial array:")
print(n)
print("\nAfter swapping")
print("\nArray :")
n[[0,-1],:]=n[[-1,0],:]
print(n)

Initial array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

After swapping

Array :
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [15]:
#10:numpy program to multiply two given arrays of same size element by element

import numpy as np 
a = np.array([[1, 3, 2],
              [4, 5, 2],
            [3,8,2]])
b = np.array([[4, 3, 1],
              [3, 4, 5],
              [4,2,1]])
print("1st array:") 
print(a)
print("2nd array:") 
print(b)
print("\nAfter multiplication:")
print("\nFinal array:")
print(np.multiply(a, b))

1st array:
[[1 3 2]
 [4 5 2]
 [3 8 2]]
2nd array:
[[4 3 1]
 [3 4 5]
 [4 2 1]]

After multiplication:

Final array:
[[ 4  9  2]
 [12 20 10]
 [12 16  2]]
